meta-llama/llama-models

- models/llama3_1/README.md
There is no need for `md5sum` as long as we do not use checksums in the download script.
> Remove md5sum requirement

- models/llama3_1/download.sh
I noticed that the `meta-llama-3.1-405b-fp8` model is missing the `fp8_scales` files. This PR adds the missing `ADDITIONAL_FILES`
> Add missing fp8_scales files to `meta-llama-3.1-405b-fp8`

- models/datatypes.py
- models/sku_list.py
Changing the SKU naming a little bit for a few reasons:
- we want to add the llama guard / prompt guard safety models to the SKUs 
- we want to factorize the SKU into two parts (a base model id + variant information) so that we can organize the several quantization formats or other variations better
- use hyphens instead of underscores for the actual IDs (much more legible, natural)
> Change how we name SKUs; add safety SKUs

- models/llama3_1/MODEL_CARD.md
This is a typo in our model_card, mmlu_pro metric for instruct models should be macro_avg/acc instead of micro_avg/acc_char.
> mmlu_pro metric should be macro_avg/acc instead of micro_avg/acc_char

- models/datatypes.py
- models/sku_list.py
* Conform the format of the model descriptors
* Sort the model list by model family
* Cut down on some copy-paste by determining props by model family 
**Before**
```
+---------------------------------------+---------------------------------------------+----------------+----------------------------+
| Model Descriptor                      | HuggingFace Repo                            | Context Length | Hardware Requirements      |
+---------------------------------------+---------------------------------------------+----------------+----------------------------+
| meta-llama/Llama-2-7b                 | meta-llama/Llama-2-7b                       | 4K             | 1 GPU, each >= 20GB VRAM   |
+---------------------------------------+---------------------------------------------+---------- …
```
> Improve model list display

- models/llama3_1/eval_details.md
Following the example in the MMLU eval details, this PR added micro-avg metrics for MMLU-Pro to eval_details.md, as many people are confused when reproducing our eval results, as they can only reproduce the micro-avg, and  have asked for this. The micro-avg can be found in the metric subset for each evals dataset but it will be easier to add it here for people to review.
> added micro-avg metrics for MMLU-Pro to eval_details.md

- README.md
We'd like to migrate users from `download.sh` to `llama download`. This command in the Llama CLI should provide a better, cross-platform experience that's also easier for us to maintain moving forward.
Before PRing, I verified I was able to use `llama download` to download models (both via `--source meta` and `--source huggingface`) on macOS, CentOS, Windows 11, and WSL (Ubuntu).
> Update README.md for llama download

- models/llama3_1/api/templates/system_message.builtin_and_custom_tools.yaml
- models/llama3_1/api/templates/system_message.custom_tools_only.yaml
- models/llama3_1/api/templates/system_message.jinja
Updated default tool call format to reflect json format message provided as a user message. 
```
llama model template --name system-builtin-and-custom-tools
```
yields the following output
> Updating tool call formats in llama cli

- README.md
Adding the `--show-all` option in the download process to list all models including older models, allowing them to be downloaded using CLI.
> Adding the show-all option to allow downloading older models

- models/llama3/reference_impl/generation.py
This CR deduplicates the `target` computation in `generation.py` for computing the token log probability with `cross_entropy`.
> Remove duplicated target computation in generation.py

- models/llama3_2/prompts_text.py
- models/llama3_2/text_prompt_format.md
Correction of a couple of minor typos of `mdoel` instead of `model`.
Example:
> Minor typos

- models/llama2/MODEL_CARD.md
- models/llama3/MODEL_CARD.md
- models/llama3_1/MODEL_CARD.md
- models/llama3_2/MODEL_CARD.md
- models/llama3_2/MODEL_CARD_VISION.md
This PR fixes broken/inconsistent links to model-specific README.md files in MODEL_CARD.md files (all Llama models now share this repo and root README.md)
Additional changes for consistency:
- Standardize feedback section for MODEL_CARD.md files for Llama 2, 3, 3.1, and 3.2 
- Remove redundant wording "Where to send questions or comments about the model"
- Minor punctuation and grammar fixes
> Update MODEL_CARD - Fix links/format, feedback section

- models/llama3/reference_impl/model.py
https://github.com/pytorch/pytorch/issues/100005
With this fix, I was able to run the model on my M1 air w/ device = 'mps'.
> torch.triu is buggy on device='mps'. Add a workaround.

- models/llama3/reference_impl/generation.py
- models/llama3/tests/api/test_generation.py
- models/scripts/example_chat_completion.py
- models/scripts/example_text_completion.py
- models/scripts/multimodal_example_chat_completion.py
- models/scripts/multimodal_example_text_completion.py
We have `Tokenizer.get_instance()` which looks up the default path using the baked in tokenizer.model in the repository anyway.
> Make `tokenizer_path` optional

- .github/workflows/gha_workflow_llama_models_tests.yml
Explicitly define write permission for PR jobs so GitHub Action integrations requiring it have full access to the workflow resources.  See [this GitHub Actions repository explanation](https://github.com/thollander/actions-comment-pull-request?tab=readme-ov-file#permissions) for details.
Also set a default value for the environment variable `api_key`.
> Explicitly define write permission for PRs within GitHub Actions workflow

- models/llama3/api/args.py
As we produce more "official" quantized models, we need a proper representation in `ModelArgs` to be able to represent the weights precisely.
> Update QuantizationArgs schema to incorporate spinquant, etc.

- models/llama3/api/datatypes.py
given this project requires pydantic>=2, this change silences warnings about using pydantic v1 features
> align with pydantic v2, @validator -> @field_validator and class Config -> model_config

- .gitignore
- models/llama3/api/chat_format.py
- models/llama3/api/datatypes.py
- models/llama3/api/interface.py
- models/llama3/api/test_tokenizer.py
- models/llama3/api/tool_utils.py
- models/llama3/prompt_templates/system_prompts.py
- models/llama3/reference_impl/generation.py
- models/llama3/tests/api/test_generation.py
- models/llama3_1/prompts.py
- models/llama3_2/prompts_text.py
- models/llama3_2/prompts_vision.py
- models/llama3_3/prompts.py
- models/prompt_format.py
- models/scripts/example_chat_completion.py
- models/scripts/multimodal_example_chat_completion.py
- models/scripts/multimodal_example_text_completion.py
This is a long-pending change and particularly important to get done now. 
Specifically:
- we cannot "localize" (aka download) any URLs from media attachments anywhere near our modeling code. it must be done upwards in the stack or in other utilities
- the PIL.Image is infesting all our APIs and that cannot be right at all. we need a standard `{ type: "image", image_url: "<...>" }` which is more extensible
- this essentially argues for separating Model-related Message types (don't have too much structure here) and the API-level Message types. As a result of this PR, `UserMessage`, etc. are moved completely to `llama-stack`.
This PR will have a substantial accompanying PR in llama-stack as well.
Ran the sole pytest test for model running:
``` …
```
> Modeling code and nearby utilities should work with "raw" bytes not URLs

- .github/workflows/gha_workflow_llama_models_tests.yml
`numpy` is missing for PR ci. Example from #227:
* https://github.com/meta-llama/llama-models/actions/runs/11997550824/job/33443281106#step:11:28
> ci: fix missing pypi packages for PR ci

- .github/workflows/publish-to-test-pypi.yml
- as title
- trusted publisher: https://test.pypi.org/manage/project/llama-models/settings/publishing/
To Use
1. Nightly triggers and make a <VERSION>.dev<DATE> package to (e.g. https://test.pypi.org/project/llama-models/0.0.63.dev20250109/)
2. Manual trigger make a <VERSION>rc<X> package to test.pypi, where <X> will be input of workflow
- Test Workflow: https://github.com/meta-llama/llama-models/actions/runs/12698757887/job/35397937186?pr=256
- Test Package: https://test.pypi.org/project/llama-models/0.0.63rc20250109/
> [CICD] github workflow for nightly testpypi llama-models package

- .github/workflows/publish-to-test-pypi.yml
- Make llama-models package build triggered by llama-stack build
- Tested in https://github.com/meta-llama/llama-stack/pull/734
> [CICD] change nightly schedule to repository_dispatch

- README.md
if you are using a model besides "Meta-Llama3.1-8B-Instruct", the path of "CHECKPOINT_DIR=~/.llama/checkpoints/Meta-Llama3.1-8B-Instruct" needs to be updated in order for the model to run
> clarifies instructions for utilizing the base model  script

- models/llama3/reference_impl/generation.py
- models/llama3/reference_impl/model.py
- models/llama3/reference_impl/multimodal/model.py
- models/llama3/tests/api/test_generation.py
This commit adds support of non-cuda pytorch backend devices to text and vision models. Commit extends existing tests to run for the externally specified device (`cuda` is a default). Commit verified on Llama3.2-3B-Instruct and Llama3.2-11B-Vision-Instruct models for:
* `cuda` device type on NVidia A10 GPU (for no regressions)
* `cpu` device type
* `xpu` device type on Intel Data Center Max Series GPU (PVC)
Note that this commit requires a fix on pytorch side for gloo torch distributed backend to restore TLS on gloo working threads. This change was merged on pytorch side and should make it to pytorch 2.6.
This PR supersedes #165 from @anordin95.
Requires: https://github.com/pytorch/pytorch/pull/142184
> feat: support non-cuda devices for text and vision models

- models/llama3/reference_impl/model.py
Found using [`torchfix`](https://github.com/pytorch-labs/torchfix).
The `apply_scaling` function used a for-loop with three conditions. The same result can be vectorised using the `torch.where` function twice (if/else).
Benchmark / test (extremely basic):
```python
import math
from time import time
import torch
def apply_scaling(freqs: torch.Tensor) -> torch.Tensor:
scale_factor = 8
low_freq_factor = 1
high_freq_factor = 4
old_context_len = 8192  # original llama3 length
low_freq_wavelen = old_context_len / low_freq_factor
high_freq_wavelen = old_context_len / high_freq_factor
new_freqs = []
for freq in freqs:
wavelen = 2 * math.pi / freq
if wavelen < high_freq_wavelen:
new_freqs.append(freq)
elif wavelen > low_freq_wavelen:
new_freqs.append(freq / scale_factor)
else:
assert …
```
> PERF: vectorise for loop using torch-native functions

- models/llama3/prompt_templates/system_prompts.py
- models/llama3/tests/prompt_templates/test_system_prompts.py
Summary:
Support user supplied prompt template in PythonListCustomToolGenerator. This is to allow user to provided their own system prompt without having to format function descirptions.
Test Plan:
python -m unittest llama_models.llama3.tests.prompt_templates.test_system_prompts
> Update PythonListCustomToolGenerator to support overriding system prompt

- models/llama3/api/chat_format.py
- models/llama3/api/tool_utils.py
Summary:
Our default tool_prompt_format is None and https://github.com/meta-llama/llama-stack/pull/1198 passed that in.
Test Plan:
Previously failing test LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/client-sdk/agents/test_agents.py::test_create_turn_response --safety-shield meta-llama/Llama-Guard-3-8B
> fix: tool_call was not encoded

- models/llama3_3/prompt_format.md
We migrated the function-calling syntax from [3.1](https://github.com/.../main/models/llama3_3/prompt_format.md) to [3.2](https://github.com/meta-llama/llama-models/blob/main/models/llama3_2/text_prompt_format.md#zero-shot-function-calling). Making the documentation consistent for 3.3.
> update llama 3.3 tool-calling syntax

- models/llama4/quantization/loader.py
```
PYTHONPATH=$(git rev-parse --show-toplevel) \
torchrun --nproc_per_node=1 \
-m models.llama4.scripts.chat_completion ../checkpoints/Llama-4-Scout-17B-16E-Instruct \
--world_size 1 \
--quantization-mode int4_mixed
```
Before this PR:
```
[rank1]: TypeError: quantize_int4() got multiple values for argument 'output_device'
```
> fix: on-the-fly int4 quantize parameter

- models/llama4/tokenizer.py
The Scout model produces these tokens, there is no point hiding them.
Will also mirror this change in llama-stack.
Add the following dialog and run chat_completion.py
```
[
RawMessage(role="system", content="Environment: ipython\nTools: brave_search, wolfram_alpha\n\n"),
RawMessage(role="user", content="What is square root of pi?"),
],
```
See:
> fix: re-add python_start, python_end tokens

- README.md
Llama 3.3 comes only in size 70B, not 11B and 90B.
> Fix Llama 3.3 model size in README

- models/llama3/tokenizer.py
- models/llama4/tokenizer.py
- models/tokenizer_utils.py
The `load_tiktoken_bpe()` function depends on blobfile to load tokenizer.model files. However, blobfile brings in pycryptodomex, which is primarily used for JWT signing in GCP - functionality we don’t require, as we always load tokenizers from local files. pycryptodomex implements its own cryptographic primitives, which are known to be problematic and insecure. While blobfile could potentially switch to the more secure PyCA cryptography library, the project appears inactive, so this transition may not happen soon. Fortunately, `load_tiktoken_bpe()` is a simple function that just reads a BPE file and returns a dictionary mapping byte sequences to their mergeable ranks. It’s straightforward enough for us to implement ourselves.
> chore: remove usage of load_tiktoken_bpe

- .gitignore
- models/llama4/chat_format.py
- models/llama4/tests/__init__.py
- models/llama4/tests/api/__init__.py
- models/llama4/tests/api/test_chat_format.py
Llama4 tool calling was causing 500 errors due to missing `arguments_json` parameter in ToolCall objects. Systems downstream expect this field to be present for proper tool execution.
- **Fixed missing `arguments_json` parameter** in `decode_assistant_message_from_content` method
- **Added comprehensive test suite** with 5 pytest-compatible tests covering:
- Custom tool calls  
- Builtin tool calls (brave_search, code_interpreter, etc.)
- Complex argument structures
- Edge cases and validation
```bash
pytest models/llama4/tests/api/test_chat_format.py -v
======= 5 passed in 1.46s =======
```
- Addresses Issue #2584 (PR #2663 reviewer feedback)
- Fixes compatibility with systems expecting `arguments_json` field
- Maintains backward compatibility with existing `arguments` field
All tool …
> fix(prompt-adapter): resolve Llama4 tool calling 500 errors
